//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRantelSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperCarEntities : DbContext
    {
        public SuperCarEntities()
            : base("name=SuperCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carreg> carregs { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<rental> rentals { get; set; }
        public DbSet<returncar> returncars { get; set; }
    }
}
